core/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('request/', views.request, name='request'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views._login, name='login'),
    path('logout/', views._logout, name='logout'),
]

djangoleave/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Dayoff(models.Model):
    create_by = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField(null=True)
    TYPE = (
        ('01', 'ลากิจ'),
        ('02', 'ลาป่วย')
    )
    type = models.CharField(max_length=2,choices=TYPE,)
    date_start = models.DateField()
    end_date = models.DateField()
    STATUS = (
        ('01', 'รอการอนุมัติ'),
        ('02', 'ไม่อนุมัติ'),
        ('03','อนุมัติ')
    )
    approve_status = models.CharField(max_length=2,choices=STATUS, default='01')

core/forms.py
from django import forms
from datetime import datetime
from .models import Dayoff


class DateInput(forms.DateInput):
    input_type = 'date'

class DayoffForm(forms.ModelForm):
    reason = forms.CharField(widget=forms.Textarea, required=False)
    class Meta:
        model = Dayoff
        exclude = ['create_by', 'approve_status']
        widgets = {
            'date_start': DateInput(),
            'end_date' : DateInput()
        }

    def clean_date_start(self):
        data = self.cleaned_data.get('date_start')

        if data < datetime.now().date():
            raise forms.ValidationError('ไม่สามารถเลือกวันในอดีตได้')
        return data

    def clean_end_date(self):
        data = self.cleaned_data.get('end_date')

        if data < datetime.now().date():
            raise forms.ValidationError('ไม่สามารถเลือกวันในอดีตได้')
        return data

    def clean(self):
        clean = super().clean()
        day1 = clean.get('date_start')
        day2 = clean.get('end_date')
        if day2 < day1:
            self.add_error('end_date', 'วันที่ไม่ถูกต้อง')

core/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.shortcuts import render, redirect

# Create your views here.
from djangoleave import settings
from .models import Dayoff
from .forms import DayoffForm
#check group
def is_employee(user):
    return user.groups.filter(name='employee').exists()

def is_in_multiple_groups(user):
    return user.groups.filter(name__in=['employee', 'manager']).exists()

def is_manager(user):
    return user.groups.filter(name='manager').exists()

@login_required()
@user_passes_test(is_in_multiple_groups)
def dashboard(req):
    dayoff = Dayoff.objects.filter(create_by=req.user).order_by('date_start')
    context = {
        'dayoff':dayoff
    }
    return render(req, 'core/dashboard.html', context)


@login_required()
@user_passes_test(is_employee, is_manager)
def request(req):
    context = {}
    if req.method == 'POST':
        form = DayoffForm(req.POST)
        if form.is_valid():
            Dayoff.objects.create(
                create_by=req.user,
                reason=form.cleaned_data.get('reason'),
                type=form.cleaned_data.get('type'),
                date_start=form.cleaned_data.get('date_start'),
                end_date=form.cleaned_data.get('end_date')

            )
            context['success'] = 'ส่งแบบฟอร์มสำเร็จ'
    else:
        form = DayoffForm()
    context['form'] = form
    return render(req, 'core/request.html', context)


#Login
def _login(req):
    context = {}
    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')
        groupname = ""
        user = authenticate(req, username=username, password=password)
        if(user):
            groupname = user.groups.get()
        print(groupname)

        if user and str(groupname) == 'employee':
            login(req, user)
            next_url = req.POST.get('next_url')  # hidden field input name
            if next_url:
                return redirect(next_url)
            else:
                return redirect('dashboard')
        elif user and str(groupname) == 'manager':
            login(req, user)
            next_url = req.POST.get('next_url')  # hidden field input name
            if next_url:
                return redirect(next_url)
            else:
                return redirect('/admin/core/dayoff/')
        else:
            error = 'Wrong username or password'
            context['username'] = username
            context['password'] = password
            context['error'] = 'Wrong username or password'

    next_url = req.GET.get('next')
    if next_url:
        print(next_url)
        context['next_url'] = next_url

    return render(req, 'core/login.html', context=context)

#Logout
def _logout(req):
    logout(req)
    return redirect('login')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% block content %}
    <h1 class="mt-5">รายงานคำขอลางานของฉัน</h1>
    <hr>
    <p>Welcome <span class="badge badge-secondary">{{ user }}</span></p>
    <div>
        {% if user.is_authenticated %}
            <a href="{% url 'request' %}" class="btn btn-primary">กรอกแบบฟอร์ม</a>
            <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
        {% endif %}
    </div>
    <br>
    <table class="table">
        <tr>
            <td>ประเภท</td>
            <td>สาเหตุ</td>
            <td>ตั้งแต่วันที่</td>
            <td>ถึงวันที่</td>
            <td>สถานะ</td>
        </tr>
        {% for off in dayoff %}
            <tr>
                <td>{{ off.get_type_display }}</td>
                <td>{{ off.reason }}</td>
                <td>{{ off.date_start }}</td>
                <td>{{ off.end_date }}</td>
                <td>
                    {#                {{ off.approve_status }}#}
                    {% if off.approve_status == '01' %}
                        <span class="badge badge-secondary">{{ off.get_approve_status_display }}</span>
                    {% elif off.approve_status == '02' %}
                        <span class="badge badge-danger">{{ off.get_approve_status_display }}</span>
                    {% elif off.approve_status == '03' %}
                        <span class="badge badge-success">{{ off.get_approve_status_display }}</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>login</h1>
    <form action="" method="post">
        {% if error %}
            <div class="alert alert-danger">
               <strong>{{ error }}</strong>
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label>Username :</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label>Password :</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group">
            <input type="hidden" name="next_url" value="{{ next_url }}">
             <input type="submit" value="Login" class="btn btn-success">
        </div>
    </form>
{% endblock %}

core/templates/core/request.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}แบบฟอร์มขอลางาน{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if success %}
            <div class="alert alert-success mt-2">
                <strong>Success!</strong> {{ success }}
            </div>
        {% endif %}
        <h1 class="mt-3">แบบฟอร์มขอลางาน</h1>
        <hr>
        <p>Welcome <span class="badge badge-secondary">{{ user }}</span></p>
        <a href="{% url 'dashboard' %}" class="btn btn-primary">view status</a>
        <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="ส่ง" class="btn btn-success w-100">
        </form>
    {% endif %}
{% endblock %}